### ISSUE TITLE
What is the meaning of "self.max_objs = 128"

### ISSUE THREAD

**Issue by songyuc** [zzzxxxttt/pytorch_simple_CenterNet_45#10]
Hi guys,
I am trying training this repo on my custom dataset,
and I want to know what the meaning of `self.max_objs = 128` is, is this mean that there must be no more than 128 objects in every image?

Your answer or idea will be appreciated!

**Comment by zzzxxxttt** [comment]
Yes, there are less than 128 objects in each image, at least for COCO dataset.

**Comment by songyuc** [comment]
Hi, @zzzxxxttt , thanks very much for your explanation and guide!
