### ISSUE TITLE
Are the "labels" referred as the indexes matching by name of the list "COCO_NAMES"? 

### ISSUE THREAD

**Issue by songyuc** [zzzxxxttt/pytorch_simple_CenterNet_45#11]
Hi, dear guys,
I am learning to train this repo on my custom dataset,
and I want to know whether the `labels`here,
![图片](https://user-images.githubusercontent.com/27288110/83990366-fd105900-a97b-11ea-9174-ea9194f3ddfc.png)
are the indexes matching by name of the list "COCO_NAMES"? 
![图片](https://user-images.githubusercontent.com/27288110/83990108-1e247a00-a97b-11ea-8a42-852774f75a38.png)

Your answer and idea will be appreciated by a beginner like me!

**Comment by zzzxxxttt** [comment]
Yes, they match.

**Comment by songyuc** [comment]
Thanks for your help!
