### ISSUE TITLE
It seems the affine transformation in the coco.py force the image into the size of 512x512

### ISSUE THREAD

**Issue by songyuc** [zzzxxxttt/pytorch_simple_CenterNet_45#12]
Hi guys,
After reading the code of `coco.py`, I find that it seems the affine transformation in the `coco.py` forces the image into the size of 512x512, as
```python
    trans_img = get_affine_transform(center, scale, 0, [self.img_size['w'], self.img_size['h']])
    img = cv2.warpAffine(img, trans_img, (self.img_size['w'], self.img_size['h']))
```
I am not sure whether this is a general trick to resize the images of different sizes.

Any idea or answer will be appreciated!

**Comment by zzzxxxttt** [comment]
It is a standard procedure for anchor-free detectors such as CornerNet/ExtremeNet/CenterNet. These models use Hourglass backbone to generate high-resolution output featuremaps, use a higher input resolution will result in a much higher computation cost.

**Comment by songyuc** [comment]
Hi, @zzzxxxttt , thanks for your guide and answer!
I think keeping the aspect ratio would be a better choice and seems more reasonable.

**Comment by zzzxxxttt** [comment]
The preprocessing keeps the aspect ratio of origainal images, it uses zero padding to make them have the same resolution.

**Comment by songyuc** [comment]
@zzzxxxttt , let me see.
More specifically, do you mean the cv2.warpAffine() function will do the zero padding for the absent part of the image?

**Comment by zzzxxxttt** [comment]
Yes
