### ISSUE TITLE
There is no nms folder in the repo

### ISSUE THREAD

**Issue by songyuc** [zzzxxxttt/pytorch_simple_CenterNet_45#13]
Hi, guys,
I am continuing learning this repo today,
and I find there is no `nms` folder in this repo, which has been imported in the test.py, as
![图片](https://user-images.githubusercontent.com/27288110/84011504-cdc41100-a9a8-11ea-86f3-6d8be2601a2b.png)
So, how can I fix this?

Your answer and idea will be appreciated!

**Comment by zzzxxxttt** [comment]
Just follow the README to install nms and run the code, I think most of your questions can be answered if you run it before opening a new issue.

**Comment by songyuc** [comment]
Hi, @zzzxxxttt ,
I am really sorry about my absent knowledge and experience,
In fact, I am just confused, as,
1. there no nms folder in the repo like,
![图片](https://user-images.githubusercontent.com/27288110/84014551-1b427d00-a9ad-11ea-8122-ef4e54429f30.png)
2. nms is in the `lib`folder as,
`cd $CenterNet_ROOT/lib/nms`
so how does 'from nms.nms import soft_nms' work, or maybe 'from lib.nms.nms import soft_nms' would work?

**Comment by zzzxxxttt** [comment]
After installing nms, it is located in your python package folder, just like you don't need a "torch" folder in your project.

**Comment by songyuc** [comment]
After looking for more information, I have known that it is a drawback within the PyCharm. But this might not influence the normal running of this repo.
Thanks sincerely again for the guide from @zzzxxxttt.
