### ISSUE TITLE
train custom data hmap_loss problem

### ISSUE THREAD

**Issue by ltss1988** [zzzxxxttt/pytorch_simple_CenterNet_45#14]
hi,Thank you for the project, I train my custom data get the hmap_loss= 9.20850 alway  the same,What could be the cause?

**Comment by zzzxxxttt** [comment]
It's hard to tell without detailed information, you can visualize the output heatmap to check whether the model learns meaningful features.

**Comment by Sdy344** [comment]
> 嗨，谢谢您的专案，我训练了我的自订资料，总是得到hmap_loss = 9.20850，可能是什么原因？

训练自己模型的时候，需要更改net文件夹里面你所用模型的num_classe为你的数据集种类数
