### ISSUE TITLE
Can you share your pre-trained model weights?

### ISSUE THREAD

**Issue by TomHeaven** [zzzxxxttt/pytorch_simple_CenterNet_45#15]
It will take a lot of time to train a model on big datasets. So can you share your pre-trained model weights on COCO or pascal-voc?

**Comment by zzzxxxttt** [comment]
I would like to, but the models are trained when I was an intern at Huawei, now my internship is over and I can't get access to the files on the company server.

**Comment by PengZH99** [comment]
if i want to inference a single image and show the results on the image,how can I achieve it quickly?I would appreciate it if you can share the inference code.thank u

**Comment by zzzxxxttt** [comment]
I've uploaded the ResDCN-18 model trained on Pascal VOC, the download link can be found in readme.
