### ISSUE TITLE
Inference 

### ISSUE THREAD

**Issue by PengZH99** [zzzxxxttt/pytorch_simple_CenterNet_45#16]
if i want to inference a single image and show the results on the image,how can I achieve it quickly?I would appreciate it if you can share the inference code.thank u

**Comment by zzzxxxttt** [comment]
Just replace the dataloader with your own image loader in test.py, and add a few lines of code to plot the results.

**Comment by PengZH99** [comment]
> Just replace the dataloader with your own image loader in test.py, and add a few lines of code to plot the results.

I've been trying all the day,but i can't  achieve it, it's so hard for me.can u help me ,thank u!

**Comment by zzzxxxttt** [comment]
I've added a demo.py in the latest commit.

**Comment by PengZH99** [comment]
> I've added a demo.py in the latest commit.

Thank u so much!
