### ISSUE TITLE
Train centernet with custom dataset

### ISSUE THREAD

**Issue by ashley-mv** [zzzxxxttt/pytorch_simple_centernet_45#17]
Hi, Could you please add what are the steps required to train this network for a new dataset and classes?

**Comment by zzzxxxttt** [comment]
1. convert your data and annotation into pascal or coco format. 
2. in `datasets/pascal.py` (or `datasets/coco.py`):
    - modify `VOC_NAMES` (or `COCO_NAMES`) to your class names
    - modify `VOC_MEAN`, `VOC_STD` (or `COCO_NAMES`, `COCO_STD`) to your dataset mean and std
    - modify `self.num_classes` to your num of classes
    - modify `self.valid_ids` to `np.arange(1, num_classes+1, dtype=np.int32)`
    - modify `self.data_dir` to your dataset location

If your dataset can not be converted to pascal or coco format, you will need to write your own dataset class.

**Comment by ashley-mv** [comment]
Thank you.

**Comment by GerardWalsh** [comment]
How can we use a pretrained model for training on our own dataset?
