### ISSUE TITLE
能详细解释下get_affine_transform的意义吗？

### ISSUE THREAD

**Issue by GYxiaOH** [zzzxxxttt/pytorch_simple_centernet_45#18]
RT...get_border函数的意义是什么？仿射变换前后的三个点是怎么取的。。。没看懂这两个地方，这个方法和resize比有什么改进吗

**Comment by zzzxxxttt** [comment]
These functions are inherited from the official CenterNet code. In my understanding, a set of affine transforms can be used to transform both the image and the bounding boxes, so we don't need to write them separately. The transform result can also be achieved using resize and random crop, which is used by [CornerNet](https://github.com/zzzxxxttt/pytorch_simple_CornerNet/blob/master/datasets/pascal.py).
