### ISSUE TITLE
AttributeError: 'list' object has no attribute 'to'

### ISSUE THREAD

**Issue by JiaLim98** [zzzxxxttt/pytorch_simple_centernet_45#20]
Hi @zzzxxxttt,

Thank you for your interesting work.

I followed everything about setting up this repo. However, when I start to train, it gives me this error. Do you know what's wrong?
![image](https://user-images.githubusercontent.com/66768413/89598648-ead56d00-d88f-11ea-9815-38bb08b2d306.png)
Hope to hear from you soon.

Regards,
JiaLim98

**Comment by zzzxxxttt** [comment]
I saw you were training on a custom dataset, what's the modification you made in the dataloader?

**Comment by JiaLim98** [comment]
I changed:
line#15 --> COCO_NAMES = 6 classes of my dataset
line#29 --> COCO_IDS = [0, 1, 2, 3, 4, 5]
line#49 --> self.num_classes = 6

That's all the changes I made to coco.py.

**Comment by zzzxxxttt** [comment]
I guess the data format of your dataset is not the same with COCO, you could train on COCO to see whether the error still occurs.

**Comment by JiaLim98** [comment]
I noticed one thing is that the COCO_NAMES should have ['_background_'] infront. Mine doesn't. Let me try to modify my annotation files (7 classes total and IDS from 0 to 7) and see if the problem persists.
Thank you.

**Comment by JiaLim98** [comment]
The issue has been solved after adding '__background__' and having Ids from 1 to 7. Now I am facing this issue
![image](https://user-images.githubusercontent.com/66768413/89604934-dcdb1880-d89e-11ea-9d29-3774644639ca.png)
I am using the default image size of 512 so it shouldn't be an issue mentioned in #19, right? I suggest it's the number of classes? This is because COCO has 80 and I'm having 7. Please advice. Thank you.

**Comment by zzzxxxttt** [comment]
Oh, the hourglass model is created with default num_classes=80, you need to change the ```num_classes``` in hourglass.py line #106.
```  def __init__(self, n, nstack, dims, modules, cnv_dim=256, num_classes=80):```

**Comment by JiaLim98** [comment]
@zzzxxxttt It is working fine now. Thank you so much!
