### ISSUE TITLE
IndexError: index 14 is out of bounds for axis 0 with size 2

### ISSUE THREAD

**Issue by dyl25984** [zzzxxxttt/pytorch_simple_centernet_45#22]
Epoch: 1 [2020-08-31 11:13:22,017]
Traceback (most recent call last):
  File "train.py", line 241, in <module>
    main()
  File "train.py", line 229, in main
    train(epoch)
  File "train.py", line 139, in train
    for batch_idx, batch in enumerate(train_loader):
IndexError: index 14 is out of bounds for axis 0 with size 2
在pascal_voc数据集上训练时出现维度问题

**Comment by zzzxxxttt** [comment]
Which version of pytorch do you use? Did you make modifications to the code?

**Comment by dyl25984** [comment]
torch1.0.0，I only replace the torch.backends.cudnn.enabled with False

**Comment by zzzxxxttt** [comment]
I guess it's related to pytorch version, could you try 1.1.0 or 1.2.0?

**Comment by dyl25984** [comment]
Maybe it's related to the machine.I try it again on my own computer instead of remote server. And it works.Both are tried in torch 1.0.
