### ISSUE TITLE
为什么test阶段需要nms？

### ISSUE THREAD

**Issue by NeuZhangQiang** [zzzxxxttt/pytorch_simple_centernet_45#31]
在看代码的时候，发现test阶段需要用到soft_nms，但是CenterNet不是号称不需要nms做后处理的嘛？我记得原文中，说是找极值，然后用前100个极值来做框。其实，我就是对这一部分有点云里雾里的。不太能理解，如果写死了取100个极值，岂不是意味着一张图就有100个框？但是，实际上一张图可能是只有3个框，4个框之类的。
作者能不能把这一步写出来呢？感谢！！！

**Comment by zzzxxxttt** [comment]
- 因为使用了翻转和多尺度测试，在同一个物体处可能会出现多个框，所以需要再用nms过滤一遍。
- 提取前100个框并不代表就一定会输出100个框，用score阈值可以过滤掉大部分框

**Comment by NeuZhangQiang** [comment]
非常感谢！
