### ISSUE TITLE
替换backbone

### ISSUE THREAD

**Issue by kp-1** [zzzxxxttt/pytorch_simple_CenterNet_45#4]
老哥，想问你一下，如果我想修改或者替换backbone，那我应该怎么做呢？我是指有没有什么格式上的要求，比如模型的返回值要包含什么之类的？

**Comment by zzzxxxttt** [comment]
backbone返回值是一个双重列表：
[ [ heatmap_1, regression_1, w_h_1 ], 
  [ heatmap_2, regression_2, w_h_2 ],
                              ...
  [ heatmap_n, regression_n, w_h_n ] ] 
前n-1个子列表是网络的中间层输出，用于做early supervision，inference的时候只用最后一个子列表

如果你不知道上面这些是什么意思，那就按这样输出就好了：
[ [ heatmap_1, regression_1, w_h_1 ] ] 

具体可以看nets/hourglass.py里的forward函数

**Comment by kp-1** [comment]
好的，谢谢！

**Comment by alibool** [comment]
> backbone返回值是一个双重列表： [ [ heatmap_1, regression_1, w_h_1 ], [ heatmap_2, regression_2, w_h_2 ], ... [ heatmap_n, regression_n, w_h_n ] ] 前n-1个子列表是网络的中间层输出，用于做early supervision，inference的时候只用最后一个子列表
> 
> 如果你不知道上面这些是什么意思，那就按这样输出就好了： [ [ heatmap_1, regression_1, w_h_1 ] ]
> 
> 具体可以看nets/hourglass.py里的forward函数

@zzzxxxttt early supervision是你自己构想么？以及你的是只在large hourglass上用到了这个技巧？
