### ISSUE TITLE
Gaussian radius implementation is wrong

### ISSUE THREAD

**Issue by kikirizki** [zzzxxxttt/pytorch_simple_CenterNet_45#5]
The official centernet repo is based on cornernet repo, the code for gaussian radius is wrong, please refer to this issue
https://github.com/princeton-vl/CornerNet/issues/110
https://github.com/Duankaiwen/CenterNet/issues/47

**Comment by zzzxxxttt** [comment]
Thanks for the comment, it is now fixed in the latest commit.

**Comment by songyuc** [comment]
Hi, @zzzxxxttt ,
I notice that the current repo calculate the `r3` like this: 
![图片](https://user-images.githubusercontent.com/27288110/84240592-db0c0780-ab30-11ea-8a48-aee672f875bc.png)
which is not divided by the `2 * a3`.
So, what is the reason here of calculating like this?

**Comment by xuezhongcailian** [comment]
same problem
