### ISSUE TITLE
可以提供一个demo么？我自己写了半天，结果不对

### ISSUE THREAD

**Issue by hyaihjq** [zzzxxxttt/pytorch_simple_CenterNet_45#6]

**Comment by zzzxxxttt** [comment]
把test.py里的dataloader部分换成自己的图片，再加几行代码把results里的框画出来就可以了

**Comment by hyaihjq** [comment]
> 把test.py里的dataloader部分换成自己的图片，再加几行代码把results里的框画出来就可以了

ok，谢谢
