### ISSUE TITLE
How can we train on our own custom dataset?

### ISSUE THREAD

**Issue by davidhuangal** [zzzxxxttt/pytorch_simple_CenterNet_45#7]

**Comment by zzzxxxttt** [comment]
Just modify the datasets/coco.py (or create a new dataset file) and implement the image reading/preprocessing part in ```__getitem__``` function, the output of ```__getitem__``` should follow the same pattern:
```
	    return {'image': img,
            'hmap': hmap, 'w_h_': w_h_, 'regs': regs, 'inds': inds, 'ind_masks': ind_masks,
            'c': center, 's': scale, 'img_id': img_id}
```

**Comment by davidhuangal** [comment]
Thank you.
