### ISSUE TITLE
请问一下，可以把计算数据集均值、方差、特征值和特征向量的代码发给我学习一下吗？

### ISSUE THREAD

**Issue by songyuc** [zzzxxxttt/pytorch_simple_CenterNet_45#9]
尊敬的开发者，你好，
我在你的代码中看到，在做数据处理时，你使用了数据集的均值、方差、特征值和特征向量这些参数；
![图片](https://user-images.githubusercontent.com/27288110/83393263-115ad000-a429-11ea-9d3a-c6f5cc60339c.png)
由于我想把你的代码适配到我自己的数据集上，但是我不太会怎么获得这个数据集的参数，你有计算这些参数的代码可以给我学习一下吗？

期待你的回复！

**Comment by zzzxxxttt** [comment]
These values are inherited from the official CenterNet code, I didn't calculate them myself. You could ask the original author for the details.

**Comment by songyuc** [comment]
Hi, @zzzxxxttt , thanks for your answer!
